export const DOCUMENT_FETCH_REQUEST = 'DOCUMENT_FETCH_REQUEST';

export const DOCUMENT_FETCH_REQUEST_FAILED = 'DOCUMENT_FETCH_REQUEST_FAILED';

export const DOCUMENT_FETCHED = 'DOCUMENT_FETCHED';

export const DOCUMENT_SELECTED = 'DOCUMENT_SELECTED';

export const PAGE_FETCH_REQUEST = 'PAGE_FETCH_REQUEST';

export const PAGE_FETCH_REQUEST_FAILED = 'PAGE_FETCH_REQUEST_FAILED';

export const PAGE_FETCHED = 'PAGE_FETCHED';

export const PAGE_SELECTED = 'PAGE_SELECTED';
